<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Message;

use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function find($entityId)
    {
        $em = $this->getEntityManager();

        $rsm = new ResultSetMappingBuilder($em);
        $rsm->addRootEntityFromClassMetadata(Message::class, 'm');

        // create native query
        $sql   = 'SELECT m.* FROM messages m WHERE m.id = :id';
        $query = $em->createNativeQuery($sql, $rsm);

        // set parameter
        $query->setParameter('id', $entityId);

        return $query->getSingleResult();
    }

    public function findAllTopLevel()
    {
        $em = $this->getEntityManager();

        $rsm = new ResultSetMappingBuilder($em);
        $rsm->addRootEntityFromClassMetadata(Message::class, 'm');

        // create native query
        $sql   = 'SELECT m.* FROM messages m WHERE m.parent_id IS NULL';
        $query = $em->createNativeQuery($sql, $rsm);

        return $query->getResult();
    }
}
